title: Portfolio
author: DonnaReilly
email: donnareillycontent@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This website is a portfolio of my work

# social links
twitter_username: https://twitter.com/Titches001
github_username:  https://github.com/DonnaReilly

show_excerpts: false #
theme: to minima
